### ISSUE TITLE
Sync crash in the field 2

### ISSUE THREAD

**Issue by jencastrodoesstuff** [digidem/mapeo-mobile#335] opened 2020-03-09 15:29 UTC
Syncing with RCA park guard device after updating to Mm v2.0.0 beta 5

![Screenshot_20200304-073541_Mapeo](https://user-images.githubusercontent.com/33264095/76229599-db76c880-61f8-11ea-9e95-f6eb50f40522.jpg)
![Screenshot_20200304-074846_One UI Home](https://user-images.githubusercontent.com/33264095/76229623-e3cf0380-61f8-11ea-9940-eca81a363840.jpg)

No details about the steps preceding these errors were provided.

**Comment by noffle** [comment] 2020-03-10 20:16
Were both devices definitely the same version?

**Comment by jencastrodoesstuff** [comment] 2020-03-10 20:22
I asked.
Was assured yes.
I can never be sure of things when I'm not verifying myself.

**Comment by noffle** [comment] 2020-03-10 23:05
The error message suggests, to me, that the devices were using different keys. However, if that's the case, they should have been on different swarms and not have seen each other in the first place.

@gmaclennan @okdistribute mapeo-core uses the key in two separate places right now: one is `opts.encryptionKey` which gets passed to multifeed for sync protocol, and `projectKey` that gets passed into mapeo-core's `join()` API. It's quite possible for a client to (accidentally?) use one key then for discovery, and another key for the sync protocol. Maybe MM has a code path where a key is set for one and not the other?

**Comment by gmaclennan** [comment] 2020-03-11 10:22
Hi @noffle, good questions. I just checked [the code](https://github.com/digidem/mapeo-mobile/blob/master/src/backend/server.js#L32-L43) and the `projectKey` is only read once, on server start, I cannot see a way `opts.encryptionKey` could get a different value than `sync.join()`.

One other idea: Is there a chance that an old `fake` hypercore on disk could take precedence? I checked through the code and it seems that multifeed switched to keeping the fake hypercore in ram at `v4.1.11`. Mapeo Mobile is using `kappa-core@4.0.1` which depends on `multifeed@4.2.2`, so I'm pretty sure that any existing `fake` will just be ignored. However, `@mapeo/core@8.1.3` (used by current Mapeo Mobile) uses `osm-p2p-syncfile@4.1.1` which pins `multifeed@4.1.10`. I'm pretty sure there is no way this older older version could ever be used by kappa-core. However, using this pinned version of multifeed in the sync file leaks the encryption key, and _maybe_ causes compatibility issues? I see it is pinned in a relatively recent [commit on 4th Feb](https://github.com/digidem/osm-p2p-syncfile/commit/e86565fd194f59a83c334abb4dd38790f8503b58) @noffle any ideas about this? However I don't think this is related to the error above, although it may cause sync file bugs.

@jencastrodoesstuff I am almost certain the device in the screenshot is not `v2.0.0 beta 5`. Ever since `v2.0.0-beta.1` the project key at the bottom of the screen is show as white text on a black background. In the screenshot it is on a blue background. This strongly suggests to me that the version screenshot is an early alpha, and this is a known error in the early alphas.

It is a real concern that alpha versions have started floating around in the field with partners - they have lots of bugs. I will take steps to remove them from Github to stop this happening in the future, and it will take some work to thoroughly check all devices and any APKs floating around to make sure they don't end up getting installed again in the future.

**Comment by gmaclennan** [comment] 2020-03-11 10:32
@jencastrodoesstuff just a follow up: I checked through the bug reporting and I see the same error reported here ("First shared hypercore must be the same") being reported multiple times on March 2nd at about 12pm local time, from Peru, on a device running v2.0.0-alpha.0. From these screenshots I can see that this error happened after this at 07:48am local time on March 4th, however the homescreen weather symbol suggests the phone has not connected to the internet since March 3rd 08:29am. We will likely not get an error report until this device connects to the internet and Mapeo is opened again whilst it is connected.

**Comment by noffle** [comment] 2020-03-11 19:52
@gmaclennan If it was running alpha.0 it would be suffering from this bug: https://github.com/digidem/mapeo-mobile/commit/105a76c877c5dded0bd60508a91696112196e4ba

This would explain the issue. I think we can close this & have folx upgrade to latest beta?

**Comment by gmaclennan** [comment] 2020-03-25 09:44
Confirmed with field staff that this was caused by syncing with alpha.0.

**Closed by gmaclennan** 2020-03-25 09:44 UTC
